env:
  browser: true
  es2021: true
extends:
  - "plugin:react/recommended"
  - standard
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  {
    quotes: ["error", "double", { "avoidEscape": true }],
    semi: ["error", "always"],
    comma-dangle: ["error", "only-multiline"],
    no-use-before-define: "off",
    multiline-ternary: ["error", "never"],
    space-before-function-paren: ["error", "never"],
  }
