development: # development connection
  type: "postgres"
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "1234"
  database: "todos"
  synchronize: true
  logging: false
  entities: ["packages/backend/src/entity/**/*.ts"]
  migrations: ["packages/backend/src/migration/**/*.ts"]
  subscribers: ["packages/backend/src/subscriber/**/*.ts"]
  cli:
    {
      "entitiesDir": "packages/backend/src/entity",
      "migrationsDir": "packages/backend/src/migration",
      "subscribersDir": "packages/backend/src/subscriber",
    }

test: # test environment connection
  type: "postgres"
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "1234"
  database: "todos_test"
  synchronize: true
  logging: false
  entities: ["packages/backend/src/entity/**/*.ts"]
  migrations: ["packages/backend/src/migration/**/*.ts"]
  subscribers: ["packages/backend/src/subscriber/**/*.ts"]
  cli:
    {
      "entitiesDir": "packages/backend/src/entity",
      "migrationsDir": "packages/backend/src/migration",
      "subscribersDir": "packages/backend/src/subscriber",
    }
